package(default_visibility = ["//visibility:public"])

# Binaries
py_binary(
	name = "converter",
	srcs = ["converter.py"],
  deps = [
    "//data/propbank/protos:frame_py_pb2",
    "//data/propbank/protos:propbank_py_pb2",
  ],
)