package(default_visibility = ["//visibility:public"])

# Libraries
py_library(
    name = "writer",
    srcs = ["writer.py"],
)

# Libraries
py_library(
    name = "reader",
    srcs = ["reader.py"],
)