package(default_visibility = ["//visibility:public"])

# Binaries.
py_binary(
	name = "main",
	srcs = ["main.py"],
	deps = [
		"//parser:dependency_parser_lib",
		"//data/treebank:treebank_py_pb2",
	],
)