package(default_visibility = ["//visibility:public"])

# Data.
filegroup(
    name = "cycles",
    srcs = glob([
        "cycles/*.pbtxt",
    ]),
)

filegroup(
    name = "connections",
    srcs = glob([
        "connections/*.pbtxt",
    ]),
)

filegroup(
    name = "msts",
    srcs = glob([
        "msts/*.pbtxt",
    ]),
)

filegroup(
    name = "generic",
    srcs = glob([
        "generic/*.pbtxt",
    ]),
)

filegroup(
	name = "tokens",
	srcs = glob([
		"tokens/*.pbtxt",
	]),
)

filegroup(
	name = "chuliuedmonds",
	srcs = glob([
		"chuliuedmonds/*.pbtxt",
	]),
)

filegroup(
	name = "common",
	srcs = glob([
		"common/*.pbtxt",
	]),
)

filegroup(
	name = "features",
	srcs = glob([
		"features/*.pbtxt",
	]),
)

filegroup(
  name = "test_features",
  srcs = glob([
    "features/test_features/*.txt",
  ]),
)

filegroup(
	name = "perceptron",
	srcs = glob([
		"perceptron/*.pbtxt",
	]),
)

filegroup(
	name = "parser",
	srcs = glob([
		"parser/*.pbtxt",
	]),
)

filegroup(
  name = "labeler",
  srcs = glob([
    "labeler/*.pbtxt",
  ]),
)

filegroup(
	name = "parser_main",
	srcs = glob([
		"parser_main/*.pbtxt",
	]),
)

filegroup(
  name = "converter",
  srcs = glob([
    "propbank/*.txt",
  ]),
)

filegroup(
  name = "preprocessor",
  srcs = glob([
    "preprocessor/*.pbtxt",
  ]),
)
