package(default_visibility = ["//visibility:public"])

# Data.
filegroup(
    name = "cycles",
    srcs = glob([
        "cycles/*.pbtxt",
    ]),
)

filegroup(
    name = "connections",
    srcs = glob([
        "connections/*.pbtxt",
    ]),
)

filegroup(
    name = "msts",
    srcs = glob([
        "msts/*.pbtxt",
    ]),
)

filegroup(
    name = "generic",
    srcs = glob([
        "generic/*.pbtxt",
    ]),
)

filegroup(
	name = "tokens",
	srcs = glob([
		"tokens/*.pbtxt",
	]),
)

filegroup(
	name = "chuliuedmonds",
	srcs = glob([
		"chuliuedmonds/*.pbtxt",
	]),
)
filegroup(
	name = "common",
	srcs = glob([
		"common/*.pbtxt",
	]),
)
filegroup(
	name = "features",
	srcs = glob([
		"features/*.pbtxt",
	]),
)
filegroup(
	name = "perceptron",
	srcs = glob([
		"perceptron/*.pbtxt",
	]),
)