# Binaries.
py_binary(
	name = "feature_extractor",
	srcs = ["feature_extractor.py"],
	deps = [
		"//data/treebank:sentence_py_pb2",
		"//mst:max_span_tree",
		"//util:reader",
		"//util:common",
	],
)