package(default_visibility = ["//visibility:public"])


py_binary(
    name = "partition_data",
    srcs = ["partition_data.py"],
    deps= [
        "//util:reader",
        "//util:writer",
        "//util:common",
    ]
)